/* --- menu items --- */
var TREE_ITEMS = [

	[' KlinikApp proiektua', '../main/home_page.htm',
		[' Portada', '../main/home_page.htm'],
		[' Laburpen Posterra', '../proiektua/4_posterra.htm'],
		[' Aurkezpena', '../proiektua/LegardaJon-azkena.pptx'],
		[' Bideo-tutoriala', '../proiektua/5_bideotutoriala.htm'],
		[' Aurkibide orokorra', '../proiektua/1_memoria/0_aurkibidea.pdf'],				
		[' Memoria', '../proiektua/0_osoa/1_memoria.pdf',
			[' M1. Sarrera', '../proiektua/1_memoria/1_sarrera.pdf'],
			[' M2. Proiektuaren Xedea', '../proiektua/1_memoria/2_proiektuaren_xedea.pdf'],
			[' M3. Aurrekariak', '../proiektua/1_memoria/3_aurrekariak.pdf'],
			[' M4. Egungo egoera', '../proiektua/1_memoria/4_egungo_egoera.pdf'],
		    [' M5. Arauak eta erreferentziak', '../proiektua/1_memoria/5_arauak_erreferentziak.pdf'],
			[' M6. Definizionak eta laburdurak', '../proiektua/1_memoria/6_definizioak_laburdurak.pdf'],
			[' M7. Hasierako betekizunak', '../proiektua/1_memoria/7_hasierako_betekizunak.pdf'],
			[' M8. Irismena', '../proiektua/1_memoria/8_irismena.pdf'],
			[' M9. Hipotesiak eta Murriztapenak', '../proiektua/1_memoria/9_hipotesiak_murriztapenak.pdf'],
			[' M10. Aukeren ikerketa eta egingarritasuna', '../proiektua/1_memoria/10_aukeren_ikerketa_egingarritasuna.pdf'],
			[' M11. Proposatutako sistemaren deskribapena', '../proiektua/1_memoria/11_proposatutako_sistemaren_deskribapena.pdf'],
	        [' M12. Arrisku analisia', '../proiektua/1_memoria/12_arrisku_analisia.pdf'],
	        [' M13. Proiektuaren antolaketa eta kudeaketa', '../proiektua/1_memoria/13_proiektuaren_antolaketa_kudeaketa.pdf'],
	        [' M14. Denbora planifikazioa', '../proiektua/1_memoria/14_denbora_planifikazioa.pdf'],
	        [' M15. Aurrekontuaren laburpena', '../proiektua/1_memoria/15_aurrekontua.pdf'],
			[' M16. Oinarrizko dokumentuen ordena', '../proiektua/1_memoria/16_dokumentu_ordena.pdf']
	    ],

		[' Memoriaren eranskinak','../proiektua/2_eranskinak/1_memoriaren_eranskinak/0_memoriaren_eranskinak.pdf',
			[' A1. Sarrerako Dokumentazioa','null',
				[' Bezeroen eskakizun ofizialak', '../Proyecto/Memoria/1_0_memoria_archivos/bezeroaren_eskakizun_ofizialak.pdf'],
				[' Enpresaren informazioa', '../Proyecto/Memoria/1_0_memoria_archivos/enpresaren_informazioa.pdf'],
			],
			[' A2. Analisi eta Diseinua','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A2_analisi_diseinua/0_A2_analisi_diseinua.pdf',
				[' Arkitektura','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A2_analisi_diseinua/1_arkitektura/0_arkitektura.pdf',
					[' Arkitektura Koadernoa','../Proyecto/Memoria/1_0_memoria_archivos/architecture_notebook.pdf'],
				],
				[' Diseinua', null,
					[' Analisi eredua','../Proyecto/Memoria/1_0_memoria_archivos/modelo-analisis-rup/index.html'],
					[' Bizagiren 1. tailerraren AMIA', '../Proyecto/Memoria/1_0_memoria_archivos/Bizagi_Txostena.pdf'],
				],
				[' Artefaktuak', null]
			],
			[' A3. Tamaina eta Esfortzu Estimazioa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A3_tamaina_esfortzu_estimazioa/0_A3_tamaina_esfortzu_estimazioak.pdf'],
			[' A4. Kudeaketa Plana','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A4_kudeaketa_plana/0_kudeaketa_plana.pdf',
				[' Integrazioaren Kudeaketa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A4_kudeaketa_plana/1_integrazio_kudeaketa.pdf'],
				[' Irismenaren Kudeaketa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A4_kudeaketa_plana/2_irismen_kudeaketa.pdf'],
				[' Epeen Kudeaketa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A4_kudeaketa_plana/3_epeen_kudeaketa.pdf'],
				[' Produktuaren Kostuen Kudeaketa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A4_kudeaketa_plana/4_kostuen_kudeaketa.pdf'],
				[' Kalitate Kudeaketa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A4_kudeaketa_plana/5_kalitatearen_kudeaketa.pdf'],
				[' Giza Baliabideen Kudeaketa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A4_kudeaketa_plana/6_giza_baliabideen_kudeaketa.pdf'],
				[' Komunikazioen Kudeaketa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A4_kudeaketa_plana/7_komunikazioen_kudeaketa.pdf'],
				[' Arriskuen Kudeaketa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A4_kudeaketa_plana/8_arriskuen_kudeaketa.pdf'],
				[' Erosketen Kudeaketa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A4_kudeaketa_plana/9_erosketen_kudeaketa.pdf'],
				[' Interesatuen Kudeaketa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A4_kudeaketa_plana/10_interesatuen_kudeaketa.pdf'],
			],
			[' A5. Segurtasun Plana','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A5_segurtasun_plana/0_A5_segurtasuna.pdf'],
			[' A6. Beste Eranskinak','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/0_A6_beste_eranskinak.pdf',
				[' Hedapena','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/1_hedapena/0_hedapena.pdf',
					[' Produktuaren dokumentazioa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/1_hedapena/1_produktuaren_dokumentazioa.pdf'],
					[' Erabiltzaile dokumentazioa - I','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/1_hedapena/2_erabiltzaile_dokumentazioa_1.pdf'],
					[' Erabiltzaile dokumentazioa - II','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/1_hedapena/2_erabiltzaile_dokumentazioa_2.pdf'],
					[' Backout Plana','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/1_hedapena/3_backout_plana.pdf'],
					[' Hedapen Plana','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/1_hedapena/4_hedapen_plana.pdf'],
					[' Azpiegitura','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/1_hedapena/5_azpiegitura.pdf']
				],
				[' Garapena','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/2_garapena/0_garapena.pdf',
					[' Garatzaileen Probak','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/2_garapena/3_garatzaileen_probak.pdf'],
					[' Diseinua - I','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/2_garapena/4_diseinua_uc1.pdf'],
					[' Diseinua - II','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/2_garapena/4_diseinua_uc2.pdf']
				],
				[' Ingurunea','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/3_ingurunea/0_ingurunea.pdf',
					[' Proiektuak Definitutako Prozesua','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/3_ingurunea/1_proiektuak_definitutako_prozesua.pdf'],
					[' Tresnak','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/3_ingurunea/2_tresnak.pdf'],
					[' Garapen Kasua','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/3_ingurunea/3_garapen_kasua.pdf']
				],
				[' Inplementazioa','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/4_inplementazioa/0_inplementazioa.pdf',
					[' Build','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/2_garapena/2_build/0_build.pdf'],
					[' Build - ZIP Folder','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/2_garapena/2_build/1_build.zip'],
					[' Inplementazioa - I','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/4_inplementazioa/1_inplementazioa_1.pdf'],
					[' Inplementazioa - II','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/4_inplementazioa/1_inplementazioa_2.pdf'],
					[' DocGenerator','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/4_inplementazioa/DocGeneratorFullPackage.zip'],
					[' RequirementTracer', '../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/4_inplementazioa/RequirementTracerFullPackage.zip']
				],
				[' Test','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/5_test/0_probak.pdf',
					[' Proba Kasuak','../Proyecto/Memoria/1_0_memoria_archivos/test_case.pdf'],
					[' Proba Log-a','../proiektua/2_eranskinak/1_memoriaren_eranskinak/A6_beste_eranskinak/5_test/2_proba_loga.pdf'],
					[' Proba Script-a','../Proyecto/Memoria/1_0_memoria_archivos/test_script.pdf']
				]
			]
		],

		[' Sistemaren Espezifikazioa','../proiektua/2_eranskinak/2_sistemaren_espezifikazioa/0_sistemaren_espezifikazioak.pdf',
			[' Glosarioa','../Proyecto/Memoria/1_0_memoria_archivos/rup_glossary.pdf'],
			[' Bisioa','../Proyecto/Memoria/1_0_memoria_archivos/vision_tpl.pdf'],
			[' Betebeharren Espezifikazioa','../Proyecto/Memoria/1_0_memoria_archivos/systemwide_req_spec.pdf'],
			[' Erabilpen-Kasuak', null,
								['01. Erregistroa', '../Proyecto/Memoria/1_0_memoria_archivos/usecase_specification_tpl_register.pdf'],
								['02. Login', '../Proyecto/Memoria/1_0_memoria_archivos/usecase_specification_tpl_login.pdf'],
								['03. Zientifikoei rola/baimena eman', '../Proyecto/Memoria/1_0_memoria_archivos/usecase_specification_tpl_zientifiko_rola_eman.pdf'],
								['04. Gida klinikoak sortu', '../Proyecto/Memoria/1_0_memoria_archivos/usecase_specification_tpl_gida_klinikoa_sortu.pdf'],
								['05. Gida klinikoak ikusi', '../Proyecto/Memoria/1_0_memoria_archivos/usecase_specification_tpl_gida_klinikoak_ikusi.pdf'],
								['06. Diagnostikoa lortu', '../Proyecto/Memoria/1_0_memoria_archivos/usecase_specification_tpl_diagnostikoa_lortu.pdf'],
							],
			[' Erabilpen Kasuen Eredua','../Proyecto/Memoria/1_0_memoria_archivos/modelo-casos-uso/index.html']
		],
		
		[' Aurrekontua','../proiektua/2_eranskinak/3_aurrekontua/0_aurrekontua.pdf',
			[' Orokortasunak', '../proiektua/2_eranskinak/3_aurrekontua/1_orokortasunak.pdf'],
			[' Edukia', '../proiektua/2_eranskinak/3_aurrekontua/2_edukia.pdf']
		],

		[' Ikerlanak','../proiektua/2_eranskinak/4_ikerlanak/0_ikerlanak.pdf',
			[' Orokortasunak', '../proiektua/2_eranskinak/4_ikerlanak/1_orokortasunak.pdf'],
			[' Edukia', '../proiektua/2_eranskinak/4_ikerlanak/2_edukia.pdf']
		]
	],

	['KlinikApp: Barne Kudeaketa', '../proiektua/3_barne_kudeaketa.htm',
		[' 1. Proiektuaren Barne Kudeaketa','../proiektua/3_proiektuaren_kudeaketa/0_proiektuaren_kudeaketa.pdf',
			[' Iterazio Plana','../Proyecto/Memoria/1_0_memoria_archivos/iteration_plan.pdf'],
			[' Proiektu Plana','../Proyecto/Memoria/1_0_memoria_archivos/project_plan.pdf'],
			[' Arrisku Zerrenda','../Proyecto/Memoria/1_0_memoria_archivos/risk_list.pdf'],
			[' Lan-Atazen Zerrenda','../Proyecto/Memoria/1_0_memoria_archivos/work_items_list.pdf'],
			[' Barne Kudeaketa','../proiektua/3_proiektuaren_kudeaketa/5_barne_kudeaketa.pdf'],
			[' Trebatzeko Materialak','../proiektua/3_proiektuaren_kudeaketa/6_trebatzeko_materialak.pdf'],
			[' Hizkuntza Hitzarmena','../proiektua/3_proiektuaren_kudeaketa/7_hizkuntza_hitzarmena.pdf'],
				[' Bilera Aktak', '../proiektua/3_proiektuaren_kudeaketa/8_aktak/0_aktak.pdf',
					['2019.02.06','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190206.pdf'],
					['2019.02.13','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190213.pdf'],
					['2019.02.20','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190220.pdf'],
					['2019.03.06 - I','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190306.pdf'],
					['2019.03.06 - II','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190306_2.pdf'],
					['2019.03.20','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190320.pdf'],
					['2019.04.02','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190402.pdf'],
					['2019.04.03','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190403.pdf'],
					['2019.04.11','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190411.pdf'],
					['2019.04.23 - I','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190423_1.pdf'],
					['2019.04.23 - II','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190423_2.pdf'],
					['2019.05.14 - I','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190514_1.pdf'],
					['2019.05.14 - II','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190514_2.pdf'],
					['2019.05.22 - I','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190522_1.pdf'],
					['2019.05.22 - II','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190522_2.pdf'],
					['2019.06.12','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190612.pdf'],
					['2019.06.17','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190617.pdf'],
					['2019.07.04','../proiektua/3_proiektuaren_kudeaketa/8_aktak/akta_20190704.pdf']
				]
		],
		[' 2. Ingurunea','',
			[' 4.1. Garapen Prozesuaren Webgunea', '../Proyecto/Memoria/1_0_memoria_archivos/SoftwareGarapenProzesua/index.html'],
			[' 4.2. Garapen Prozesua (BPMN fitxategia)', '../Proyecto/Memoria/1_0_memoria_archivos/SoftwareGarapenProzesua.bpm'],
			[' 4.3. Garapen Kasua dokumentua', '../Proyecto/Memoria/1_0_memoria_archivos/ErabakienJustifikazioak.pdf'],
			[' 4.4. Garapen Prozesuaren Planifikazioa', '../Proyecto/Memoria/1_0_memoria_archivos/DenboraEstimazioak.pdf'],
			[' 4.5. Garapen Prozesuren Inplementazio Ideiak', '...'],
			[' 4.6. Tresnak', '...'],
		],
	]					
];